<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->posts() as $i => $data) {
            Post::updateOrCreate(
                ['slug' => Str::slug($data['title'])],
                [
                    ...$data,
                    'published_at' => now()->subDays(($i + 1) * 6),
                    'is_active' => true,
                ]
            );
        }
    }

    private function posts(): array
    {
        return [
            [
                'title' => 'Chest pain at night: when to wait and when to call an ambulance',
                'category' => 'health-tips', 'author' => 'Prof. Dr. Ashraful Haque', 'read_minutes' => 6,
                'is_featured' => true,
                'excerpt' => 'Most chest pain is not a heart attack. But a few specific features change the calculation entirely, and they are worth knowing before you are the one deciding at 3am.',
                'body' => "Most chest pain that arrives in our emergency department turns out not to be cardiac. Acid reflux, muscular strain and anxiety account for a large share of presentations. That is genuinely reassuring — but it is also why people talk themselves out of coming in when they should not.\n\n## The features that should not wait\n\nCall an ambulance, rather than driving yourself, if chest discomfort comes with any of the following:\n\n- Pressure, heaviness or tightness rather than a sharp stab, lasting more than a few minutes\n- Pain spreading to the jaw, neck, left arm or between the shoulder blades\n- Sweating that appears alongside the pain, particularly cold sweat\n- Breathlessness out of proportion to what you were doing\n- Nausea or vomiting together with the discomfort\n- A sense of impending doom — patients describe this often, and it deserves to be taken seriously\n\n## Why the ambulance rather than a car\n\nThis is the part people get wrong most often. An advanced life-support ambulance carries a defibrillator and a paramedic who can record an ECG and transmit it ahead. If the rhythm deteriorates in a private car in Dhaka traffic, nothing can be done. If it deteriorates in an ambulance, it can be shocked within seconds.\n\nIt also means the receiving team knows what is coming. When our emergency department gets an ECG before the patient arrives, the catheterisation laboratory can be activated in advance, which removes twenty to thirty minutes from the treatment time.\n\n## Women, and why the pattern is often different\n\nWomen having heart attacks are more likely to present without the textbook crushing central chest pain. Fatigue that is out of character, breathlessness, nausea and upper back discomfort can all be the dominant symptom. This is a substantial reason why women are diagnosed later and treated later. If something feels significantly wrong and you cannot explain it, get it checked.\n\n## What happens when you arrive\n\nYou will be triaged within minutes and have an ECG almost immediately — this is not a queue you wait in. If the ECG shows a blocked artery, you go directly to the catheterisation laboratory. If it does not, blood tests for cardiac enzymes are taken and repeated a few hours later, because early tests can be normal in a heart attack that is still evolving.\n\nBeing sent home after investigation is a good outcome, not a wasted trip.",
            ],
            [
                'title' => 'Dengue season: the warning signs that mean go to hospital now',
                'category' => 'health-tips', 'author' => 'Dr. Naeem Uddin Bhuiyan', 'read_minutes' => 5,
                'is_featured' => true,
                'excerpt' => 'The dangerous phase of dengue often begins as the fever comes down, not while it is at its peak. Here is what to watch for.',
                'body' => "Dengue follows a pattern that catches families out every monsoon, because the most dangerous period does not look like the most dangerous period.\n\n## The three phases\n\n**Febrile phase (days 1–3).** High fever, severe headache, pain behind the eyes, muscle and joint aches. Unpleasant, but usually not the risky part.\n\n**Critical phase (days 4–6).** The fever settles. Many families relax here — and this is precisely when plasma leakage can begin. Most severe dengue complications occur in this window.\n\n**Recovery phase (day 7 onwards).** Appetite returns and a rash may appear as things improve.\n\n## Warning signs that need hospital assessment\n\nGo to a hospital immediately if any of these appear, particularly as the fever falls:\n\n- Severe or persistent abdominal pain\n- Persistent vomiting — more than three times in an hour\n- Bleeding from gums or nose, or blood in vomit or stool\n- Black, tarry stools\n- Lethargy, restlessness or unusual irritability\n- Cold, clammy hands and feet\n- Passing much less urine than usual\n- Difficulty breathing\n\n## Managing the mild case at home\n\nParacetamol is the only fever medicine that is safe. Do not take ibuprofen, aspirin, diclofenac or any similar anti-inflammatory — they increase bleeding risk in dengue and we see avoidable complications from this every season.\n\nFluid intake matters more than any medication. Oral saline, coconut water, rice water, soup and plain water are all appropriate. Aim for pale urine passed at least every four to six hours.\n\nHave a platelet count and haematocrit checked daily from day three, and keep the results so trends are visible. A single value tells you far less than a direction of travel.\n\n## Preventing it in the first place\n\nAedes mosquitoes breed in clean, still water and bite during the day. Empty and scrub anything holding water — flower pot trays, buckets, discarded containers, air-conditioner drip trays, water tank lids — twice a week. The scrubbing matters, because eggs stick to the sides and survive drying.",
            ],
            [
                'title' => 'RBR Hospital opens a second cardiac catheterisation laboratory',
                'category' => 'news', 'author' => 'RBR Hospital', 'read_minutes' => 3,
                'excerpt' => 'The new lab doubles capacity for emergency angioplasty and removes the waiting time that previously built up when both an emergency and a planned case arrived together.',
                'body' => "RBR Hospital has commissioned a second cardiac catheterisation laboratory, doubling capacity for both emergency and planned coronary intervention.\n\nThe practical effect is on emergency care. Previously, a single laboratory meant that a heart attack arriving during a planned procedure had to wait for the room to clear. With two laboratories, one can be kept available for primary angioplasty at all times.\n\n\"Door-to-balloon time is the single strongest predictor of how much heart muscle a patient keeps,\" said Professor Dr. Ashraful Haque, Head of Interventional Cardiology. \"Our median has been under sixty minutes. With the second laboratory we expect to bring that down further, and more importantly to remove the occasional long outlier when two emergencies arrived together.\"\n\nThe new laboratory is equipped with flat-panel digital imaging with reduced radiation dose, intravascular ultrasound and fractional flow reserve measurement for assessing borderline narrowings, and a rotational atherectomy system for heavily calcified arteries.\n\nThe unit is operational now and accepts emergency referrals from other hospitals through the emergency hotline on 10666.",
            ],
            [
                'title' => 'Five numbers every adult over 35 should know about themselves',
                'category' => 'health-tips', 'author' => 'Prof. Dr. Abdul Matin Sarker', 'read_minutes' => 5,
                'excerpt' => 'Blood pressure, HbA1c, LDL cholesterol, waist circumference and eGFR. Between them, they predict most of what will go wrong, and all five are cheap to measure.',
                'body' => "Preventive medicine is unglamorous. But a small number of measurements predict a large share of what actually shortens life in Bangladesh, and none of them is expensive to check.\n\n## 1. Blood pressure\n\n**Target: under 130/80 mmHg for most adults.**\n\nHigh blood pressure causes no symptoms until it causes a stroke. It is the leading modifiable risk factor for stroke, and stroke is one of the leading causes of death and disability here. Have it checked at least annually — and if it is raised once, have it rechecked properly rather than dismissed.\n\n## 2. HbA1c\n\n**Target: under 5.7% is normal; 5.7–6.4% is prediabetes; 6.5% or above indicates diabetes.**\n\nHbA1c reflects the average glucose over roughly three months, so it cannot be gamed by fasting the night before. Bangladesh has a high and rising prevalence of type 2 diabetes, and a substantial proportion of cases are undiagnosed. Prediabetes is reversible with weight loss and activity — that window is worth catching.\n\n## 3. LDL cholesterol\n\n**Target: under 100 mg/dL for most; under 70 mg/dL if you already have heart disease or diabetes.**\n\nLDL is the fraction that drives arterial plaque. South Asians tend to develop coronary disease earlier and at lower body weights than European populations, so a normal BMI is not reassurance on its own.\n\n## 4. Waist circumference\n\n**Target: under 90 cm for men, under 80 cm for women.**\n\nFor South Asian populations, waist measurement predicts metabolic risk better than BMI does, because the fat distribution differs. A tape measure costs almost nothing and tells you something a weighing scale does not.\n\n## 5. eGFR\n\n**Target: above 60 mL/min/1.73m².**\n\nEstimated glomerular filtration rate, calculated from serum creatinine, reflects kidney function. Chronic kidney disease is silent until it is advanced, and diabetes and hypertension are the two leading causes — which is exactly why the first four numbers matter for this one.\n\n## What to do with them\n\nWrite them down with the date, and keep the list. A single reading is a snapshot; five years of readings is a trajectory, and a trajectory is what lets a physician act early rather than react late.",
            ],
            [
                'title' => 'Newborn hearing screening is now offered to every baby born here',
                'category' => 'news', 'author' => 'RBR Hospital', 'read_minutes' => 3,
                'excerpt' => 'Congenital hearing loss affects a small but meaningful number of newborns, and detecting it in the first months changes language outcomes substantially.',
                'body' => "Every baby delivered at RBR Hospital is now offered hearing screening before discharge, as a routine part of newborn care rather than a test parents have to know to ask for.\n\nThe screening uses otoacoustic emission testing, which is painless, takes a few minutes, and is usually done while the baby sleeps. Babies who do not pass the initial screen are recalled for a fuller assessment; most turn out to have normal hearing, with the initial result explained by fluid or debris in the ear canal.\n\nThe rationale is timing. Language development depends on hearing during the first months and years of life. Without screening, congenital hearing loss is often not identified until a child is two or three years old and not speaking — by which point a significant developmental window has closed. Detected in the first months, hearing aids or cochlear implantation can be arranged early enough that language development proceeds close to normally.\n\n\"The test is quick and cheap, and the consequence of missing it is measured in years of a child's development,\" said Dr. Mizanur Rahman Khan, Head of ENT. \"There was no good argument for making it optional.\"\n\nThe service is included in the maternity package at no additional charge. Babies born elsewhere can be booked for screening through the ENT department.",
            ],
            [
                'title' => 'Before you take that antibiotic: four questions worth asking',
                'category' => 'health-tips', 'author' => 'Dr. Naeem Uddin Bhuiyan', 'read_minutes' => 4,
                'excerpt' => 'Antibiotic resistance in Bangladesh is now high enough that some routine infections are difficult to treat. Much of the driver is avoidable.',
                'body' => "Antibiotics are among the most valuable medicines ever developed, and we are steadily using them into ineffectiveness. Resistance rates for several common organisms in Bangladesh are now high enough that infections which were once straightforward require second- or third-line drugs.\n\nMost of the driver is not exotic. It is antibiotics taken for viral illness, bought without prescription, and stopped early.\n\n## Four questions worth asking\n\n**1. Is this infection actually bacterial?**\n\nMost sore throats, colds, coughs and cases of flu are viral. Antibiotics do nothing for them — no faster recovery, no reduced complications — while still contributing to resistance and side effects. Green nasal discharge is not evidence of bacterial infection; it is normal in the course of a viral cold.\n\n**2. Is this the narrowest drug that will work?**\n\nBroad-spectrum antibiotics kill a wider range of organisms, including the useful ones in your gut, and select more strongly for resistance. Where a narrow-spectrum drug will treat the likely organism, it is the better choice.\n\n**3. Should we culture first?**\n\nFor urinary infections, wound infections and recurrent problems, a culture and sensitivity test identifies the actual organism and which drugs it responds to. It takes a day or two, but it replaces guessing with knowing — and for recurrent infection, guessing has usually already failed.\n\n**4. How long, exactly?**\n\nCourse lengths have shortened for many infections as evidence has accumulated. Ask for the specific number of days and complete it. Stopping when you feel better leaves the hardiest organisms behind, which is precisely the population you do not want surviving.\n\n## What not to do\n\nDo not buy antibiotics without a prescription. Do not use leftover antibiotics from a previous illness. Do not take someone else's. Do not press a doctor for an antibiotic for a viral illness — and if a doctor explains why one is not needed, that is good medicine, not indifference.",
            ],
        ];
    }
}
